---
title: "Capstone project 2 topics"
author: "Ray Gunawidjaja"
date: "March 14, 2018"
---


#### Topic 1: Automated literature review and experimental design using NLP, regex, and machine learning algorithms

This project will involve two main objectives, which are as follows:

<p>
<i>1. Automated  literature search</i> <br>
- A list of relevant literature references will be searched using (e.g., google scholar database, https://scholar.google.com/) and filtered for relevance with the aid of NLP and regex techniques. 
- The relevant documents will be downloaded as PDF documents.
</p>
<p>
<i>2. Automated experimental design</i> <br>
- Experimental parameters from each document will be extracted and analyzed for similarities and for common trends, from which a new set of more efficient experiments will be designed. 
</p>

#### Topic 2: Object recognition via a webcam using opencv and machine learning algorithms

This project will involve two main objectives, which are as follows:

<p>
<i>1. Train a machine learning model using labelled images of known objects</i> <br>
- Labelled training datasets of known objects will be downloaded from, e.g., http://deeplearning.net/datasets/. 
</p>
<p>
<i>2. Automated experimental design</i> <br>
- Incorporate machine learning algorithm to a webcam via opencv to allow an online, autonomous object recognition of arbitrary objects that the webcam sees.
</p>


#### Topic 3: Time-series analysis using recurrent neural network algorithms

This project will involve two main objectives, which are as follows:

<p>
<i>1. Analyze time-series data</i> <br>
- Time-series data will be downloaded from,e.g., https://timeseries.weebly.com/data-sets.html.
- Time-series data will be analyzed for trends and seasonality.
</p>
<p>
<i>2. Fit time series data to an appropriate model</i> <br>
- An appropriate recurrent neural network model will be designed and optimized to allow foward and backward time series prediction.
</p>

